CREATE TABLE artists (
     id BIGSERIAL PRIMARY KEY,
     name VARCHAR(120) NOT NULL,
     biography TEXT,
     country VARCHAR(80),
     active BOOLEAN NOT NULL DEFAULT TRUE,
     created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);